### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by shouldsee** [umbrellabeach/music-generation-with-DL#1]
麻烦能不能把文章的abstract贴出来啊

**Comment by umbrellabeach** [comment]
Hi 考虑到格式的简洁性（参考 https://github.com/zhangqianhui/AdversarialNetsPapers 、 https://github.com/nightrome/really-awesome-gan  ），暂时不显示abstract。将来会对文献做tag以方便检索，谢谢关注~
